interface SkillOption {
    label: string;
    value: string;
}
const SkillList: SkillOption[] = [
    { label: 'JavaScript', value: 'javascript' },
    { label: 'TypeScript', value: 'typescript' },
    { label: 'Python', value: 'python' },
    { label: 'Java', value: 'java' },
    { label: 'C++', value: 'cpp' },
    { label: 'C#', value: 'csharp' },
    { label: 'Go', value: 'go' },
    { label: 'Ruby', value: 'ruby' },
    { label: 'PHP', value: 'php' },
    { label: 'Swift', value: 'swift' },
    { label: 'Kotlin', value: 'kotlin' },
    { label: 'SQL', value: 'sql' },
    { label: 'NoSQL', value: 'nosql' },
    { label: 'React', value: 'react' },
    { label: 'Angular', value: 'angular' },
    { label: 'Vue.js', value: 'vuejs' },
    { label: 'Node.js', value: 'nodejs' },
    { label: 'Express', value: 'express' },
    { label: 'Django', value: 'django' },
    { label: 'Flask', value: 'flask' },
    { label: 'Spring Boot', value: 'springboot' },
    { label: 'Ruby on Rails', value: 'rails' },
    { label: 'TensorFlow', value: 'tensorflow' },
    { label: 'PyTorch', value: 'pytorch' },
    { label: 'Docker', value: 'docker' },
    { label: 'Kubernetes', value: 'kubernetes' },
    { label: 'AWS', value: 'aws' },
    { label: 'Azure', value: 'azure' },
    { label: 'Google Cloud', value: 'gcp' },
    { label: 'CI/CD', value: 'cicd' },
    { label: 'Git', value: 'git' },
    { label: 'Agile Methodologies', value: 'agile' },
    { label: 'Scrum', value: 'scrum' },
    { label: 'JIRA', value: 'jira' },
    { label: 'TDD', value: 'tdd' },
    { label: 'BDD', value: 'bdd' },
    { label: 'Linux', value: 'linux' },
    { label: 'Unix', value: 'unix' },
    { label: 'Bash', value: 'bash' },
    { label: 'Shell Scripting', value: 'shell' },
    { label: 'RESTful APIs', value: 'restapi' },
    { label: 'GraphQL', value: 'graphql' },
    { label: 'Microservices', value: 'microservices' },
    { label: 'System Design', value: 'systemdesign' },
    { label: 'Data Structures', value: 'datastructures' },
    { label: 'Algorithms', value: 'algorithms' },
    { label: 'Networking', value: 'networking' },
    { label: 'Cybersecurity', value: 'cybersecurity' },
    { label: 'Machine Learning', value: 'ml' },
    { label: 'Data Science', value: 'datascience' },
    { label: 'DevOps', value: 'devops' },
    { label: 'Cloud Computing', value: 'cloud' },
    { label: 'Blockchain', value: 'blockchain' },
    { label: 'AI/ML', value: 'ai_ml' },
    { label: 'IoT', value: 'iot' },
    { label: 'Big Data', value: 'bigdata' },
    { label: 'SaaS', value: 'saas' },
    { label: 'PaaS', value: 'paas' },
    { label: 'FaaS', value: 'faas' },
    { label: 'Edge Computing', value: 'edgecomputing' },
    { label: 'AR/VR', value: 'arvr' },
    // Add more skills as needed...
];
export default SkillList;