interface SkillOption {
  label: string;
  value: string;
}
const SkillList: SkillOption[] = [
  // Programming Languages
  { label: 'JavaScript', value: 'javascript' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'Python', value: 'python' },
  { label: 'Java', value: 'java' },
  { label: 'C++', value: 'cpp' },
  { label: 'C#', value: 'csharp' },
  { label: 'C', value: 'c' },
  { label: 'Go', value: 'go' },
  { label: 'Rust', value: 'rust' },
  { label: 'Ruby', value: 'ruby' },
  { label: 'PHP', value: 'php' },
  { label: 'Swift', value: 'swift' },
  { label: 'Kotlin', value: 'kotlin' },
  { label: 'Scala', value: 'scala' },
  { label: 'R', value: 'r' },
  { label: 'MATLAB', value: 'matlab' },
  { label: 'Perl', value: 'perl' },
  { label: 'Dart', value: 'dart' },
  { label: 'Elixir', value: 'elixir' },
  { label: 'Haskell', value: 'haskell' },
  { label: 'Clojure', value: 'clojure' },
  { label: 'F#', value: 'fsharp' },
  { label: 'Objective-C', value: 'objectivec' },
  { label: 'Assembly', value: 'assembly' },
  { label: 'COBOL', value: 'cobol' },
  { label: 'Fortran', value: 'fortran' },

  // Frontend Technologies
  { label: 'React', value: 'react' },
  { label: 'Angular', value: 'angular' },
  { label: 'Vue.js', value: 'vuejs' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Nuxt.js', value: 'nuxtjs' },
  { label: 'Gatsby', value: 'gatsby' },
  { label: 'HTML5', value: 'html5' },
  { label: 'CSS3', value: 'css3' },
  { label: 'SASS/SCSS', value: 'sass' },
  { label: 'LESS', value: 'less' },
  { label: 'Tailwind CSS', value: 'tailwindcss' },
  { label: 'Bootstrap', value: 'bootstrap' },
  { label: 'Material-UI', value: 'materialui' },
  { label: 'Ant Design', value: 'antdesign' },
  { label: 'Chakra UI', value: 'chakraui' },
  { label: 'Styled Components', value: 'styledcomponents' },
  { label: 'Emotion', value: 'emotion' },
  { label: 'jQuery', value: 'jquery' },
  { label: 'D3.js', value: 'd3js' },
  { label: 'Three.js', value: 'threejs' },
  { label: 'WebGL', value: 'webgl' },
  { label: 'Canvas API', value: 'canvas' },
  { label: 'Web Components', value: 'webcomponents' },
  { label: 'Progressive Web Apps', value: 'pwa' },
  { label: 'Responsive Design', value: 'responsivedesign' },
  { label: 'Cross-browser Compatibility', value: 'crossbrowser' },
  { label: 'Accessibility (a11y)', value: 'accessibility' },
  { label: 'SEO', value: 'seo' },

  // Backend Technologies
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Express.js', value: 'express' },
  { label: 'Koa.js', value: 'koajs' },
  { label: 'Fastify', value: 'fastify' },
  { label: 'NestJS', value: 'nestjs' },
  { label: 'Django', value: 'django' },
  { label: 'Flask', value: 'flask' },
  { label: 'FastAPI', value: 'fastapi' },
  { label: 'Spring Boot', value: 'springboot' },
  { label: 'Spring Framework', value: 'spring' },
  { label: 'Ruby on Rails', value: 'rails' },
  { label: 'Sinatra', value: 'sinatra' },
  { label: 'Laravel', value: 'laravel' },
  { label: 'Symfony', value: 'symfony' },
  { label: 'CodeIgniter', value: 'codeigniter' },
  { label: 'ASP.NET', value: 'aspnet' },
  { label: '.NET Core', value: 'dotnetcore' },
  { label: 'Gin', value: 'gin' },
  { label: 'Echo', value: 'echo' },
  { label: 'Fiber', value: 'fiber' },
  { label: 'Phoenix', value: 'phoenix' },
  { label: 'Actix', value: 'actix' },
  { label: 'Rocket', value: 'rocket' },

  // Databases
  { label: 'MySQL', value: 'mysql' },
  { label: 'PostgreSQL', value: 'postgresql' },
  { label: 'SQLite', value: 'sqlite' },
  { label: 'Microsoft SQL Server', value: 'sqlserver' },
  { label: 'Oracle Database', value: 'oracle' },
  { label: 'MongoDB', value: 'mongodb' },
  { label: 'Redis', value: 'redis' },
  { label: 'Elasticsearch', value: 'elasticsearch' },
  { label: 'Cassandra', value: 'cassandra' },
  { label: 'DynamoDB', value: 'dynamodb' },
  { label: 'CouchDB', value: 'couchdb' },
  { label: 'Neo4j', value: 'neo4j' },
  { label: 'InfluxDB', value: 'influxdb' },
  { label: 'Firebase Firestore', value: 'firestore' },
  { label: 'Supabase', value: 'supabase' },
  { label: 'PlanetScale', value: 'planetscale' },
  { label: 'FaunaDB', value: 'faunadb' },
  { label: 'TimescaleDB', value: 'timescaledb' },

  // Cloud Platforms
  { label: 'AWS', value: 'aws' },
  { label: 'Azure', value: 'azure' },
  { label: 'Google Cloud Platform', value: 'gcp' },
  { label: 'DigitalOcean', value: 'digitalocean' },
  { label: 'Heroku', value: 'heroku' },
  { label: 'Vercel', value: 'vercel' },
  { label: 'Netlify', value: 'netlify' },
  { label: 'Railway', value: 'railway' },
  { label: 'Render', value: 'render' },
  { label: 'Fly.io', value: 'flyio' },
  { label: 'Cloudflare', value: 'cloudflare' },
  { label: 'Firebase', value: 'firebase' },
  { label: 'Amplify', value: 'amplify' },

  // DevOps & Tools
  { label: 'Docker', value: 'docker' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'Jenkins', value: 'jenkins' },
  { label: 'GitHub Actions', value: 'githubactions' },
  { label: 'GitLab CI/CD', value: 'gitlabci' },
  { label: 'CircleCI', value: 'circleci' },
  { label: 'Travis CI', value: 'travisci' },
  { label: 'Terraform', value: 'terraform' },
  { label: 'Ansible', value: 'ansible' },
  { label: 'Chef', value: 'chef' },
  { label: 'Puppet', value: 'puppet' },
  { label: 'Vagrant', value: 'vagrant' },
  { label: 'Helm', value: 'helm' },
  { label: 'ArgoCD', value: 'argocd' },
  { label: 'Prometheus', value: 'prometheus' },
  { label: 'Grafana', value: 'grafana' },
  { label: 'ELK Stack', value: 'elk' },
  { label: 'Splunk', value: 'splunk' },
  { label: 'New Relic', value: 'newrelic' },
  { label: 'Datadog', value: 'datadog' },

  // Version Control
  { label: 'Git', value: 'git' },
  { label: 'GitHub', value: 'github' },
  { label: 'GitLab', value: 'gitlab' },
  { label: 'Bitbucket', value: 'bitbucket' },
  { label: 'SVN', value: 'svn' },
  { label: 'Mercurial', value: 'mercurial' },

  // Testing
  { label: 'Jest', value: 'jest' },
  { label: 'Mocha', value: 'mocha' },
  { label: 'Chai', value: 'chai' },
  { label: 'Cypress', value: 'cypress' },
  { label: 'Selenium', value: 'selenium' },
  { label: 'Playwright', value: 'playwright' },
  { label: 'Puppeteer', value: 'puppeteer' },
  { label: 'JUnit', value: 'junit' },
  { label: 'TestNG', value: 'testng' },
  { label: 'PyTest', value: 'pytest' },
  { label: 'RSpec', value: 'rspec' },
  { label: 'PHPUnit', value: 'phpunit' },
  { label: 'Postman', value: 'postman' },
  { label: 'Insomnia', value: 'insomnia' },
  { label: 'K6', value: 'k6' },
  { label: 'JMeter', value: 'jmeter' },

  // Mobile Development
  { label: 'React Native', value: 'reactnative' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'Ionic', value: 'ionic' },
  { label: 'Xamarin', value: 'xamarin' },
  { label: 'Cordova/PhoneGap', value: 'cordova' },
  { label: 'Android Development', value: 'android' },
  { label: 'iOS Development', value: 'ios' },
  { label: 'SwiftUI', value: 'swiftui' },
  { label: 'Jetpack Compose', value: 'jetpackcompose' },

  // Data Science & ML
  { label: 'TensorFlow', value: 'tensorflow' },
  { label: 'PyTorch', value: 'pytorch' },
  { label: 'Keras', value: 'keras' },
  { label: 'Scikit-learn', value: 'scikitlearn' },
  { label: 'Pandas', value: 'pandas' },
  { label: 'NumPy', value: 'numpy' },
  { label: 'Matplotlib', value: 'matplotlib' },
  { label: 'Seaborn', value: 'seaborn' },
  { label: 'Plotly', value: 'plotly' },
  { label: 'Jupyter', value: 'jupyter' },
  { label: 'Apache Spark', value: 'spark' },
  { label: 'Hadoop', value: 'hadoop' },
  { label: 'Kafka', value: 'kafka' },
  { label: 'Airflow', value: 'airflow' },
  { label: 'MLflow', value: 'mlflow' },
  { label: 'Kubeflow', value: 'kubeflow' },
  { label: 'OpenCV', value: 'opencv' },
  { label: 'NLTK', value: 'nltk' },
  { label: 'spaCy', value: 'spacy' },
  { label: 'Hugging Face', value: 'huggingface' },

  // APIs & Integration
  { label: 'REST APIs', value: 'restapi' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'gRPC', value: 'grpc' },
  { label: 'WebSockets', value: 'websockets' },
  { label: 'Socket.io', value: 'socketio' },
  { label: 'Webhooks', value: 'webhooks' },
  { label: 'OAuth', value: 'oauth' },
  { label: 'JWT', value: 'jwt' },
  { label: 'OpenAPI/Swagger', value: 'openapi' },
  { label: 'Postman', value: 'postman' },

  // Architecture & Design Patterns
  { label: 'Microservices', value: 'microservices' },
  { label: 'Monolithic Architecture', value: 'monolithic' },
  { label: 'Serverless', value: 'serverless' },
  { label: 'Event-Driven Architecture', value: 'eventdriven' },
  { label: 'Domain-Driven Design', value: 'ddd' },
  { label: 'CQRS', value: 'cqrs' },
  { label: 'Event Sourcing', value: 'eventsourcing' },
  { label: 'Clean Architecture', value: 'cleanarchitecture' },
  { label: 'Hexagonal Architecture', value: 'hexagonal' },
  { label: 'MVC', value: 'mvc' },
  { label: 'MVP', value: 'mvp' },
  { label: 'MVVM', value: 'mvvm' },
  { label: 'Observer Pattern', value: 'observer' },
  { label: 'Factory Pattern', value: 'factory' },
  { label: 'Singleton Pattern', value: 'singleton' },
  { label: 'Strategy Pattern', value: 'strategy' },

  // Methodologies
  { label: 'Agile', value: 'agile' },
  { label: 'Scrum', value: 'scrum' },
  { label: 'Kanban', value: 'kanban' },
  { label: 'Lean', value: 'lean' },
  { label: 'DevOps', value: 'devops' },
  { label: 'TDD', value: 'tdd' },
  { label: 'BDD', value: 'bdd' },
  { label: 'DDD', value: 'ddd' },
  { label: 'Pair Programming', value: 'pairprogramming' },
  { label: 'Code Review', value: 'codereview' },
  { label: 'Continuous Integration', value: 'ci' },
  { label: 'Continuous Deployment', value: 'cd' },

  // Operating Systems
  { label: 'Linux', value: 'linux' },
  { label: 'Ubuntu', value: 'ubuntu' },
  { label: 'CentOS', value: 'centos' },
  { label: 'Red Hat', value: 'redhat' },
  { label: 'Debian', value: 'debian' },
  { label: 'macOS', value: 'macos' },
  { label: 'Windows', value: 'windows' },
  { label: 'Unix', value: 'unix' },
  { label: 'FreeBSD', value: 'freebsd' },

  // Tools & IDEs
  { label: 'VS Code', value: 'vscode' },
  { label: 'IntelliJ IDEA', value: 'intellij' },
  { label: 'Eclipse', value: 'eclipse' },
  { label: 'Vim', value: 'vim' },
  { label: 'Emacs', value: 'emacs' },
  { label: 'Sublime Text', value: 'sublime' },
  { label: 'Atom', value: 'atom' },
  { label: 'WebStorm', value: 'webstorm' },
  { label: 'PyCharm', value: 'pycharm' },
  { label: 'Android Studio', value: 'androidstudio' },
  { label: 'Xcode', value: 'xcode' },
  { label: 'Visual Studio', value: 'visualstudio' },

  // Project Management
  { label: 'JIRA', value: 'jira' },
  { label: 'Trello', value: 'trello' },
  { label: 'Asana', value: 'asana' },
  { label: 'Monday.com', value: 'monday' },
  { label: 'Notion', value: 'notion' },
  { label: 'Confluence', value: 'confluence' },
  { label: 'Slack', value: 'slack' },
  { label: 'Microsoft Teams', value: 'teams' },
  { label: 'Discord', value: 'discord' },

  // Security
  { label: 'Cybersecurity', value: 'cybersecurity' },
  { label: 'Penetration Testing', value: 'pentesting' },
  { label: 'OWASP', value: 'owasp' },
  { label: 'SSL/TLS', value: 'ssltls' },
  { label: 'Encryption', value: 'encryption' },
  { label: 'Authentication', value: 'authentication' },
  { label: 'Authorization', value: 'authorization' },
  { label: 'GDPR Compliance', value: 'gdpr' },
  { label: 'SOC 2', value: 'soc2' },
  { label: 'ISO 27001', value: 'iso27001' },

  // Emerging Technologies
  { label: 'Blockchain', value: 'blockchain' },
  { label: 'Ethereum', value: 'ethereum' },
  { label: 'Smart Contracts', value: 'smartcontracts' },
  { label: 'Web3', value: 'web3' },
  { label: 'NFTs', value: 'nfts' },
  { label: 'DeFi', value: 'defi' },
  { label: 'IoT', value: 'iot' },
  { label: 'Edge Computing', value: 'edgecomputing' },
  { label: 'AR/VR', value: 'arvr' },
  { label: 'Quantum Computing', value: 'quantum' },
  { label: 'Robotics', value: 'robotics' },
  { label: '5G', value: '5g' },

  // Soft Skills
  { label: 'Leadership', value: 'leadership' },
  { label: 'Team Management', value: 'teammanagement' },
  { label: 'Communication', value: 'communication' },
  { label: 'Problem Solving', value: 'problemsolving' },
  { label: 'Critical Thinking', value: 'criticalthinking' },
  { label: 'Project Management', value: 'projectmanagement' },
  { label: 'Mentoring', value: 'mentoring' },
  { label: 'Public Speaking', value: 'publicspeaking' },
  { label: 'Technical Writing', value: 'technicalwriting' },
  { label: 'Requirements Analysis', value: 'requirementsanalysis' },
  { label: 'Stakeholder Management', value: 'stakeholdermanagement' },
  { label: 'Time Management', value: 'timemanagement' },
  { label: 'Adaptability', value: 'adaptability' },
  { label: 'Innovation', value: 'innovation' },
  { label: 'Strategic Thinking', value: 'strategicthinking' },
];
export default SkillList;
